[
  {
    userId: 3,
    firstName: "mohamad",
    middleName: "ashraf",
    lastName: "abdin",
    role: "TEAM_LEAD",
    email: "moh.abdin27@gmail.com",
    users: [],
    service: "CONTRACT_MANAG",
    services: [],
    team: "L2",
  },
  {
    userId: 934,
    firstName: "mohamad",
    middleName: "ashraf",
    lastName: "abdin",
    role: "MEMBER",
    email: "ahmad@gmail.com",
    users: [],
    service: "CONTRACT_MANAG",
    services: [],
  },
  {
    userId: 971,
    firstName: "aaa",
    middleName: "aa",
    lastName: "aaaa",
    role: "MEMBER",
    email: "aaaaa123@gmail.com",
    users: [],
    service: "CHANGE_OCUP",
    services: [],
  },
  {
    userId: 4,
    firstName: "mohamad",
    middleName: "ashraf",
    lastName: "abdin",
    role: "TEAM_LEAD",
    email: "mohamad@gmail.com",
    users: [],
    service: "USER_MANAG",
    services: [],
    team: "L2",
  },
  {
    userId: 1,
    firstName: "BB1",
    middleName: "BBB",
    lastName: "BBBB",
    role: "MEMBER",
    email: "BB123@inspirejo.com",
    users: [],
    service: "CONTRACT_MANAG",
    services: [
      { authId: 12, name: "PM_ROLE", description: "PM Role" },
      { authId: 10, name: "OC_ROLE", description: "OC Role" },
      { authId: 2, name: "SUPER_VISOR", description: "SuperVisor" },
      { authId: 11, name: "CO_ROLE", description: "CO Role" },
      { authId: 7, name: "MANUAL_VISAS", description: "Manual Visas" },
      { authId: 8, name: "VISAS", description: "Visas" },
    ],
    team: "L2",
  },
  {
    userId: 976,
    firstName: "aaa",
    middleName: "aa",
    lastName: "aaaa",
    role: "MEMBER",
    email: "aaaa123@gmail.com",
    users: [],
    service: "CONTRACT_MANAG",
    services: [],
  },
  {
    userId: 1324,
    firstName: "mohamad",
    middleName: "ashraf",
    lastName: "abdin",
    role: "MEMBER",
    email: "rand@gmail.com",
    users: [],
    service: "WORK_PERMIT",
    services: [],
  },
  {
    userId: 1473,
    firstName: "mohamad",
    middleName: "ashraf",
    lastName: "abdin",
    role: "MEMBER",
    email: "samer@gmail.com",
    users: [],
    service: "",
    services: [],
  },
  {
    userId: 1475,
    firstName: "mohamad",
    middleName: "ashraf",
    lastName: "abdin",
    role: "MEMBER",
    email: "samer1@gmail.com",
    users: [],
    service: "",
    services: [],
  },
];
